language: generic
sudo: true
dist: trusty
addons:
  apt:
    packages:
    - unzip
    - wget
script:
  - |
    wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
    unzip terraform_0.11.5_linux_amd64.zip
    sudo mv terraform /usr/bin/terraform
    ./deploy.sh
if: tag IS present
